services:
  - type: web
    name: maq-ai-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyDuaCjU-SIQyA-gsJIetBMgaLMqIY_aIus
