services:
  - type: web
    name: maq-ai-assistant
    env: python
    buildCommand: pip install -r requirements.txt
-   startCommand: python app.py
+   startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyDuaCjU-SIQyA-gsJIetBMgaLMqIY_aIus
